issuer: https://issuer.enforce.dev
audience: https://console-api.enforce.dev
subject_pattern: "[a-f0-9]+"
claim_pattern:
  email: ".*@chainguard.dev"

permissions:
  contents: write
  pull_requests: write
